// GENERATED by scripts/seed-demo/generate.py — do not edit by hand.
// Each post is a REAL output of the Akroma Spark backend pipeline,
// produced once and baked as a fixed asset.

export interface DemoPostData {
  niche: string;
  handle: string;
  displayName: string;
  topic: string;
  headline: string;
  image: string;
  caption: string;
}

export const DEMO_POSTS: DemoPostData[] = [
  {
    niche: 'fitness',
    handle: 'gympower.oficial',
    displayName: 'GymPower Academia',
    topic: `O fim do treino até a falha em 2026`,
    headline: `Treinar até a falha é erro amador.`,
    image: 'assets/demo/fitness.png',
    caption: `92% de quem 'treina pesado' está apenas inflamando o corpo sem ganhar 1g de músculo.

Em 2026, volume de treino é métrica de ego. Na GymPower, os sensores de fadiga miofascial provaram: quem descansa 3 minutos entre séries hipertrofia 40% mais que o apressadinho do bi-set. O segredo não é o esforço, é a precisão da tensão mecânica monitorada por IA.

A nutrição evoluiu para o 'Precision Peptide Timing'. Se você ainda toma whey genérico sem olhar seu gráfico de glicose em tempo real no app da academia, está jogando performance no lixo. Disciplina sem dado é apenas suor inútil e inflamação sistêmica desnecessária. 🧬

Você treina para postar no espelho ou para bater recordes reais de força? Comenta sua carga atual no agachamento.

#gympower #academiasp #treinodeforca #biohackingbrasil #performance2026 #hipertrofiareal #nutricaoesportiva #recuperacaomuscular #treinointeligente #saopaulofit #metas2026 #forçabruta #dadosfitness #tecnologianoesporte #musclemonitoring`,
  },
  {
    niche: 'tecnologia',
    handle: 'devpro.br',
    displayName: 'DevPro Brasil',
    topic: `A morte do Senior tradicional e a ascensão do Orquestrador`,
    headline: `O Sênior morreu. O Orquestrador assumiu o comando.`,
    image: 'assets/demo/tecnologia.png',
    caption: `Junior ganhando R$18k. Senior ganhando R$12k. Como?

Em 2026, tempo de casa virou custo fixo irrelevante. O mercado parou de pagar por "linhas de código" e começou a pagar por "gestão de contexto". Quem ainda foca em sintaxe virou commodity barata frente aos modelos Llama-5 e GPT-6o.

O novo Senior não codifica, ele orquestra enxames de agentes autônomos. Vi Tech Leads na DevPro dobrando o faturamento ao migrar do legado para arquiteturas de Intent-based Infra, onde o código é gerado e destruído em segundos. ⚡️

Se você ainda se orgulha de dominar um framework, você é o próximo na fila do layoff. A elite agora domina orquestração de inferência e redução de latência de agentes. 🧠

E aí, você prefere ser o piloto da IA ou a peça que ela vai substituir? 👇

#devpro #tecnologia #programacao #aiagents #llmops #rustlang #softwarearchitecture #techleadership #cloudcomputing2026 #aiorchestration #futureofwork #seniorit #backendengineering #systemdesign`,
  },
  {
    niche: 'gastronomia',
    handle: 'chefana.cozinha',
    displayName: 'Chef Ana Ribeiro',
    topic: `O fim da tradição: a física por trás da Carbonara perfeita.`,
    headline: `A Carbonara perfeita não é tradição. É física.`,
    image: 'assets/demo/gastronomia.png',
    caption: `Parem de fingir: 94% dos chefs amadores destroem a Carbonara por medo da física.

Em 2026, a obsessão pela 'tradição' virou desculpa para técnica medíocre. A ciência da gordura prova que o guanciale precisa atingir exatos 68°C para liberar os aminoácidos certos sem queimar a gordura. Se você joga o ovo na massa fervendo, você não está cozinhando, está fazendo omelete com macarrão.

Usei o método de 'fricção controlada' no meu último jantar privativo em SP e o feedback foi unânime: textura de veludo, zero resíduo de óleo. A gastronomia italiana evoluiu, e quem fica preso apenas no livro da vovó está servindo nostalgia, não sabor. 🤌

Você prefere seguir a tradição cega ou a ciência que entrega resultado impecável?

#chefana #gastronomia #cozinhaitaliana #foodscience #carbonara #tecnicaculinaria #altagastronomia #gastronomiasp #privatechef #foodphysics #cozinhaprofissional #tendencias2026 #culinariaitaliana #masterclass #chefskills`,
  },
  {
    niche: 'moda',
    handle: 'lolastyle.br',
    displayName: 'Lola Martins — Stylist',
    topic: `O fim do fast fashion e a fraude do guarda-roupa lotado`,
    headline: `Armário cheio é sintoma de um estilo vazio.`,
    image: 'assets/demo/moda.png',
    caption: `90% das mulheres compram 30 peças por ano, mas só usam 6.

A verdade dói: você está enterrando dinheiro em poliéster descartável enquanto a taxa de carbono sobre sintéticos subiu 40% este mês. Ter um guarda-roupa lotado em 2026 não é sinal de status, é sinal de amadorismo e falta de repertório visual.

O novo luxo é a Cápsula Analógica: 12 peças de fibras naturais que comunicam mais autoridade que qualquer trend do TikTok. Quem domina o custo por uso não compra roupa, investe em ativos de imagem que duram uma década.

Você prefere ter 50 blusinhas de R$ 90 ou 5 peças que te fazem parecer a CEO da própria vida? 

#lolastyle #moda #stylisttips #capsulewardrobe2026 #quietluxury #minimalismobrasil #estiloprofissional #consumoconsciente #modainteligente #lookdodiareal #mulheresdenegocios #armariocapsula #sustentabilidadefashion`,
  },
  {
    niche: 'juridico',
    handle: 'dra.patricia.costa',
    displayName: 'Dra. Patricia Costa — OAB/SP',
    topic: `O fim do preço abusivo por algoritmo e IAs`,
    headline: `Preço Justo vs. Discriminação por Algoritmo`,
    image: 'assets/demo/juridico.png',
    caption: `74% dos brasileiros pagam mais caro em apps de transporte e delivery sem saber o motivo.

O STJ acaba de sinalizar: algoritmos de precificação dinâmica que rastreiam sua bateria baixa ou urgência são abusivos. Não é apenas 'oferta e procura', é discriminação digital. Se o app sabe que você está desesperado, ele não pode te punir com uma tarifa 3x maior.

Em 2026, o CDC finalmente alcançou a caixa-preta das IAs. O ônus da prova agora é da plataforma: elas precisam provar a transparência do cálculo, não você. O jogo virou para quem entende de vulnerabilidade digital.

Você já sentiu que o preço subiu só porque você precisava muito daquele serviço agora?

#direitodoconsumidor #oabsp #advogada #direitodigital2026 #stj #consumidorconsciente #algoritmos #precificacaodinamica #iaresponsavel #protecaodedados #justicadigital #cdc2026 #vulnerabilidadedigital #direitostech`,
  },
  {
    niche: 'imobiliario',
    handle: 'rafael.imoveis',
    displayName: 'Rafael Mendes — Corretor CRECI 54321',
    topic: `Por que comprar imóvel em 2026 virou erro estratégico`,
    headline: `2026: Comprar imóvel virou queima de capital`,
    image: 'assets/demo/imobiliario.png',
    caption: `9 em cada 10 investidores estão perdendo 4% ao ano por puro ego imobiliário.

Com a Selic estabilizada em 9,25% e o m2 no Itaim Bibi cruzando os R$ 55 mil, a conta da 'casa própria' parou de fechar para o topo da pirâmide. Quem ainda busca rentabilidade em aluguel residencial tradicional está sendo engolido pela valorização artificial do CUB e pela vacância de ativos mal posicionados.

O jogo agora é tokenização de RWA e liquidez imediata. Enquanto você espera a valorização de um tijolo físico na Vila Nova Conceição, o capital institucional já migrou para galpões logísticos fracionados com yields de 14% a.a. isentos de IR. O tijolo físico virou passivo emocional, não ativo financeiro. 📉

Você prefere a segurança de um contrato de 30 meses ou a liquidez de um ativo digital que rende o dobro? 

#rafaelimoveis #mercadoimobiliario #imovelsp #investimentoimobiliario #selic2026 #itaimbibi #vilanovaconceicao #tokenizacao #rwa #mercadofinanceiro #realestatebrazil #viverdealuguel #m2sp #estrategiafinanceira #analiseimobiliaria`,
  },
  {
    niche: 'educacao',
    handle: 'profmarcos.estudos',
    displayName: 'Prof. Marcos — Metodo de Estudos',
    topic: `Por que resumos coloridos estão matando sua aprovação em 2026`,
    headline: `Sua canetinha colorida está te reprovando.`,
    image: 'assets/demo/educacao.png',
    caption: `93% dos aprovados em Medicina este ano ignoraram o cronograma tradicional.

Em 2026, fazer resumo linear é o caminho mais rápido para a reprovação. A neurociência prova que o cérebro ignora padrões passivos e previsíveis. Enquanto você gasta horas colorindo títulos, seu concorrente usa Recuperação Ativa Dinâmica para hackear a curva de esquecimento em tempo real.

Dados do último Simulado Nacional mostram que o foco médio caiu para 12 minutos. Tentar estudar 4 horas seguidas é suicídio intelectual e gera 'brain fog' irreversível. O segredo da aprovação não é o volume de horas, mas a saturação sináptica controlada em blocos de alta intensidade.

Você prefere o conforto do resumo que não funciona ou a dor do método que aprova?

#profmarcos #metododeestudos #vestibular #neurocienciaaplicada #concursos2026 #aprendizadoacelerado #focoultra #estudointeligente #retencaodedados #produtividadeacademica #vestibulandos2026 #performancecerebral #metodofeynman`,
  },
  {
    niche: 'saude',
    handle: 'dra.juliana.nutrologa',
    displayName: 'Dra. Juliana Alves — Nutrologa',
    topic: `A farsa do exame de sangue 'normal' em 2026`,
    headline: `Seu exame 'normal' é um erro sistêmico.`,
    image: 'assets/demo/saude.png',
    caption: `Seu exame de sangue diz 'normal', mas suas células estão pedindo socorro.

Em 2026, confiar apenas em valores de referência laboratoriais é como tentar dirigir um Tesla usando um mapa de papel de 1990. Estamos na era da medicina de precisão, onde a flexibilidade metabólica e o monitoramento contínuo de biomarcadores valem mais do que qualquer check-up anual estático.

Vejo pacientes de 35 anos com exames 'dentro da média', mas com uma diversidade de microbiota equivalente a um idoso de 80. O erro? Ignorar que a inflamação silenciosa e a senescência celular não esperam o sintoma aparecer para destruir sua longevidade. O foco mudou: não tratamos números, otimizamos fenótipos.

Se você ainda baseia sua saúde em 'não sentir dor', você já está atrasado na corrida contra o envelhecimento biológico. A nutrologia moderna não é sobre comer menos, é sobre sinalização celular e silenciamento de genes inflamatórios através de nutrientes específicos para o SEU DNA.

Você confia mais no que sente ao acordar ou no papel impresso que o laboratório te entrega? Me conta nos comentários.

#drajuliana #nutrologia #saudepreventiva #longevidade #medicinadeprecisao #microbioma #saudemetabolica #biohackingbr #envelhecimentosudavel #epigenetica #saudeintestinal #nutrologiasp #performancehumana #vidallonga #checkup2026`,
  },
];
